select
        id as event_id,
        whoid as who_id,
        whatid as what_id,
        whocount as who_count,
        whatcount as what_count,
        subject,
        location,
        activitydatetime ,
        activitydate,
        durationinminutes,
        startdatetime,
        enddatetime,
        enddate,
        description,
        accountid,
        ownerid,
        currencyisocode,
        type,
        isdeleted,
        ischild,
        isgroupevent,
        groupeventtype,
        createddate,
        createdbyid,
        lastmodifieddate,
        lastmodifiedbyid,
        systemmodstamp,
        recurrenceactivityid,
        isrecurrence,
        recurrencestartdatetime,
        recurrenceenddateonly,
        recurrencetimezonesidkey,
        recurrencetype,
        recurrenceinterval,
        recurrencedayofweekmask,
        recurrencedayofmonth,
        recurrencemonthofyear,
        isreminderset,
        eventsubtype,
        isrecurrence2exclusion,
        isrecurrence2,
        isrecurrence2exception,
        dp_type__c,
        dp_account__c,
        dp_related_to_id__c,
        dp_related_to_working_list__c,
        dp_service_area__c,
        dp_salesforce_18_digit_id__c,
        activity_summary_field__c,
        dp_iscurrentuserassignedto__c,
        dp_name_id__c,
        dp_kroll_brand_outreach__c,
        dp_meeting_objective__c,
        dp_product_step__c,
        dp_digital_solution__c,
        dp_owner_service_line__c,
FROM {{source('uat-sfdc', 'sfdc_event')}}
